export const paymentTexts = {
    en: {
      complete_purchase: "Complete your purchase by providing us with your payment details",
      first_name: "First Name",
      last_name: "Last Name", 
      full_name: "Full Name",
      email_address: "Email Address",
      phone_number: "Phone Number",
      ticket_count: "Number of Tickets",
      credit_card_number: "Credit Card Number",
      cardholder_name: "Cardholder Name",
      valid_until: "Valid Until",
      cvv: "CVV",
      authorize_payment: "Authorize Payment",
      cancel: "Cancel",
      processing: "Processing...",
      
      // Placeholders
      first_name_placeholder: "Enter your first name",
      last_name_placeholder: "Enter your last name",
      full_name_placeholder: "Enter your full name",
      email_placeholder: "Enter your email address",
      phone_placeholder: "Enter your phone number",
      ticket_count_placeholder: "4",
      card_number_placeholder: "1234 5678 9012 3456",
      cardholder_placeholder: "Name on card",
      valid_until_placeholder: "MM/YY",
      cvv_placeholder: "123",
      
      // Validation messages
      first_name_required: "First name is required",
      last_name_required: "Last name is required",
      email_required: "Email is required",
      email_invalid: "Please enter a valid email address",
      phone_required: "Phone number is required",
      phone_invalid: "Please enter a valid phone number",
      card_number_required: "Credit card number is required",
      cardholder_required: "Cardholder name is required",
      expiry_required: "Expiry date is required",
      cvv_required: "CVV is required",
      payment_error: "Payment failed. Please try again.",
      
      // Additional text
      minimum_tickets_warning: "Minimum 4 tickets required for group booking",
    },
    
    am: {
      complete_purchase: "Ավարտեք ձեր գնումը՝ տրամադրելով մեզ ձեր վճարման մանրամասները",
      first_name: "Անուն",
      last_name: "Ազգանուն",
      full_name: "Անուն Ազգանուն",
      email_address: "Էլ. փոստի հասցե",
      phone_number: "Հեռախոսահամար",
      ticket_count: "Տոմսերի քանակ",
      credit_card_number: "Վարկային քարտի համար",
      cardholder_name: "Քարտակիրի անուն",
      valid_until: "Վավեր է մինչև",
      cvv: "CVV",
      authorize_payment: "Վճարման լիազորում",
      cancel: "Չեղարկել",
      processing: "Մշակվում է...",
      
      // Placeholders
      first_name_placeholder: "Մուտքագրեք ձեր անունը",
      last_name_placeholder: "Մուտքագրեք ձեր ազգանունը",
      full_name_placeholder: "Մուտքագրեք ձեր անուն ազգանունը",
      email_placeholder: "Մուտքագրեք ձեր էլ. փոստը",
      phone_placeholder: "Մուտքագրեք ձեր հեռախոսահամարը",
      ticket_count_placeholder: "4",
      card_number_placeholder: "1234 5678 9012 3456",
      cardholder_placeholder: "Քարտի վրա գրված անունը",
      valid_until_placeholder: "ԱԱ/ՏՏ",
      cvv_placeholder: "123",
      
      // Validation messages
      first_name_required: "Անունը պարտադիր է",
      last_name_required: "Ազգանունը պարտադիր է",
      email_required: "Էլ. փոստը պարտադիր է",
      email_invalid: "Խնդրում ենք մուտքագրել վավեր էլ. փոստ",
      phone_required: "Հեռախոսահամարը պարտադիր է",
      phone_invalid: "Խնդրում ենք մուտքագրել վավեր հեռախոսահամար",
      card_number_required: "Վարկային քարտի համարը պարտադիր է",
      cardholder_required: "Քարտակիրի անունը պարտադիր է",
      expiry_required: "Ժամկետը պարտադիր է",
      cvv_required: "CVV-ը պարտադիր է",
      payment_error: "Վճարումը ձախողվեց: Խնդրում ենք կրկին փորձել:",
      
      // Additional text
      minimum_tickets_warning: "Խմբային ամրագրման համար նվազագույնը 4 տոմս է պահանջվում",
    },
    
    ru: {
      complete_purchase: "Завершите покупку, предоставив нам данные для оплаты",
      first_name: "Имя",
      last_name: "Фамилия",
      full_name: "Полное имя",
      email_address: "Адрес электронной почты",
      phone_number: "Номер телефона",
      ticket_count: "Количество билетов",
      credit_card_number: "Номер кредитной карты",
      cardholder_name: "Имя держателя карты",
      valid_until: "Действительна до",
      cvv: "CVV",
      authorize_payment: "Авторизовать платеж",
      cancel: "Отмена",
      processing: "Обработка...",
      
      // Placeholders
      first_name_placeholder: "Введите ваше имя",
      last_name_placeholder: "Введите вашу фамилию",
      full_name_placeholder: "Введите ваше полное имя",
      email_placeholder: "Введите ваш email",
      phone_placeholder: "Введите ваш номер телефона",
      ticket_count_placeholder: "4",
      card_number_placeholder: "1234 5678 9012 3456",
      cardholder_placeholder: "Имя на карте",
      valid_until_placeholder: "ММ/ГГ",
      cvv_placeholder: "123",
      
      // Validation messages
      first_name_required: "Имя обязательно",
      last_name_required: "Фамилия обязательна",
      email_required: "Email обязателен",
      email_invalid: "Пожалуйста, введите действительный email",
      phone_required: "Номер телефона обязателен",
      phone_invalid: "Пожалуйста, введите действительный номер телефона",
      card_number_required: "Номер кредитной карты обязателен",
      cardholder_required: "Имя держателя карты обязательно",
      expiry_required: "Срок действия обязателен",
      cvv_required: "CVV обязателен",
      payment_error: "Платеж не прошел. Пожалуйста, попробуйте еще раз.",
      
      // Additional text
      minimum_tickets_warning: "Для группового бронирования требуется минимум 4 билета",
    },
  }