export const texts = {
  am: {
    'home': 'Մեր Մասին',
    'tours': 'Տուրեր',
    'history': 'Մեր Մասին',
    'wines': 'Գինիներ',
    'grapes': 'Տերուար',
    'payment': 'payment',
    'historyTitle': 'Պատմություն եվ արժեքներ',
    'historyText': 'Խաղողագործության և գինեգործության բնօրրան Հայաստանում 6100 ամյա ավանդույթները փոխանցվել են սերնդից սերունդ՝ հասնելով մինչև մեր օրեր:Արևմտյան Հայաստանից Արարատյան դաշտավայրի հնագույն գինեգործական ավանդույթներով հայտնի պատմական Արմավիր մայրաքաղաքի Բլուր թաղամասի տարածք տեղափոխված մեր պապերը հիմնել են այգիներ, 1890-ականներին կառուցել են գինու հնձան, գետնափոր մառան և ավանդույթի ուժով պատրաստել սեփական գինին՝ փոխանցելով այդ գիտելիքներն ու հմտությունները սերնդեսերունդ:Ունենալով պապերից ժառանգված գինեգործական ավանդույթներ՝ գինու պատրաստման հարմարություններ և ստորգետնյա մառան, գինու պատրաստման ու խմելու գործընթացը մշտապես եղել է Ջրաղացպանյան ընտանիքի առօրեայի անբաժանելի մասը:Արևահամ խաղողի, վերամշակման ավանդական եղանակների և ժառանգված ավանդույթների հա-մադրություններից են ստեղծվում Ջրաղացպանյան գինիները՝ ձեռք բերելով բացառիկ համահոտային երանգներ:Այգու խաղողի խինդ ու պարով բերքահավաքի, զօր ու գիշեր սիրով ընթացող վերամշակման, խմորման խնամքով հսկողության ու հետևողական հասունացման համադրման արդյունքում է ծնվում Ջրաղացպանյան գինիների յուրաքանչյուր կաթիլը:',
    'grapesTitle': 'Տերուար',
    'grapesText': 'Խաղողի գինիների համար որպես հումք օգտագործվում է գինու գործարանի գտնվելու վայրի՝ Արմավիրի մարզի Բամբակաշատ գյուղի այգիներ խաղողը: Խաղողի որոշ մասը մթերվում է նաև մեր այգիներից (2հա), որոնք ծրագրում ենք ընդլայնել նոր մոտեցումներով և բացառապես հայկական սորտերով՝ բացահայտելով նրանց գինեգործական ներուժը։ Գինեգործարանն ու խաղողի այգիները գտնվում են Արարատյան դաշտավայրում՝ Արմավիրի մարզի  Բամբակաշատ գյուղում: Գյուղը տեղակայված է Արարատյան հարթավայրի մեջտեղում, ունի բերրի հողեր, որոնք նպաստավոր են հողագործությամ համար: Ծովի մակարդակից բարձրությունը՝ 860մ:Հողի տեսակները - Ողողվող գորշ մարգագետնային հողերը ձևավորվել են Արարատյան հարթավայրում՝ 800-950 մ բարձրության վրա՝ բնահողի, մակերեսային խոնավության և մարդկային բազմա-դարյան գործունեության արդյունքում։ Հումուսային շերտի խորությունը կազմում է 80-120 սմ։ Հողը բնութագրվում է կարբոնատների բարձր՝ (3-7 %) և հումուսի ցածր՝ (1,5-2,0 %) պարունակությամբ, կավային և ավազակավային մեխանի-կական բաղադրությամբ։ Հողի ալկալիական ռեակցիան՝ 8.2-8.5: Հողը հիմնականում աղակալված չէ, սակայն հանդիպում են տարածքներ, որոնք ընդերքի հանքային ջրերի ազդեցությամբ թույլ աղակալված են և ալկալիացված չեն։ Հողի ներծծման միջին գործակիցը կազմում է 30-40 մգ։ Ունի բավարար ջրաֆիզիկական բնույթ։ Հողի տեսակը որոշ հատվածներում գորշ-կիսաանապատային է: Բնութագրվում է հումուսի բարակ շերտով (25-40 սմ) և նրա ցածր պարունակությամբ (2%), քարքարոտությամբ և կար-բոնատների նշանակալի քանակությամբ, գիպսային շերտով և ներծծման ցածր գործակցով (20-30 մգ), ջրաֆիզիկական անբավարար բնույթով: Նրանք հարուստ են հողալ-կալիական հիմքերով (pH=7.5-8.5), որոշ տեղերում ունեն աղային բնույթ: Ալկալիացված հողեր հանդիպում են գույնզգույն կավե շերտերի վրա, Երևանի մոտակայքում։ Բնութագրվում են բաժան-բաժան լինելով, ծավալի փոքրությամբ, կավային մեխանի-կական կազմով, հումուսի (0,8-2,6 %) և կարբոնատների (4-12 %) քիչ պարունակությամբ, (0.8-2.5%) աղակալմամբ, թույլ ալկալիական ռեակցիայով, գիպսացիայով և ներծծման միջին ընդունակությամբ։ Ունի ոչ բարվոք ջրաֆիզիկական բնույթ։',
    'toursTitle': 'Տուրիստական այցեր',
    'toursText': 'Ընկերությունում հատուկ կարևորություն ունեն տուրիստական այցերի կազմակերպումը, որոնց ընթացքում բացի ընդունված համտեսից ու շրջայցից 130 ամյա մառանում և նոր կառուցված գործարանում, ցանկացողների համար կարող են անցկացվել տարաբնույթ ուսուցողական և տեղեկատվական վարպետության դասեր, այցելուները կարող են  մասնակցել որոշ արտադրական գործընթացներին և այլն',
    'line1': "Ջրաղացպանյան",
    'line2': "Բամբակ",
  },
  ru: {
    'home': 'Главная',
    'tours': 'Туры',
    'history': 'О Нас',
    'about': "О нас",
    'wines': 'Вино',
    'social': "Соцсети",
    'terroir': "Терруар",
    team: "Команда",
    contact: "Контакты",
    'grapes': 'Терруар',
    'payment': 'payment',
    'historyTitle': 'История и ценности',
    'historyText': 'В Армении, колыбели виноградарства и виноделия, 6100-летние традиции передаются из поколения в поколение, дойдя до наших дней.Наши предки, переехавшие из западной Армении в район Блур исторической столицы Армавира, славящейся своими древними винодельческими традициями, посадили виноградники, в 1890-х годах построили винный погреб и традиционно производили собственные вина, передавая традиции новым поколениям.Имея винодельческие традиции, унаследованные от предков, винодельческие приспособление и подземный погреб, процесс изготовления вина и ежедневного сочетания его с едой всегда были неотъемлемой частью повседневной жизни семьи Джрагацпанян.Вина Jarghatspanyan создаются из сочетания солнечного винограда, традиционных методов обработки и унаследованных традиций, приобретая исключительные ароматические оттенки.Сочетание винограда, собранного в традиционной атмосфере песен и танцев, неустанной обработки, бдительного контроля процесса брожения и гармоничного созревания рождается каждая капля вина Джрагацпанян.',
    'grapesTitle': 'Терруар',
    'grapesText': 'Как сырье для производства виноградных вин используются виноград из виноградникиах села Бамбакашат Армавирской области. Часть обработанного винограда с наших виноградников (2 га), которые мы планируем расширять с использованием новых подходов, исключительно армянскими сортами, проверяя их винодельческий потенциал. Винодельня и виноградники расположены в Араратской долине, в селе Бамбакашат Армавирской области. Село расположено посреди Араратской равнины, имеет плодородные земли, благоприятные для земледелия. Высота над уровнем моря 860м. Тип почв - Аллювиальные серо-луговые почвы образовались на Араратской равнине на высоте 800-950 м в результате почвенного, поверхностного увлажнения и многовековой деятельности человека. Мощность гумусового слоя 80-120 см. Почва характеризуется высоким содержанием карбонатов (3-7 %) и низким содержанием гумуса (1,5-2,0 %), глинистым и супесчаным механическим составом. Щелочная реакция почвы: 8,2-8,5. Почва в основном незасоленная, но есть участки слабозасоленные и не засоленные из-за влияния минеральных вод в недрах. Средний коэффициент поглощения почвы составляет 30-40 мг. Имеет достаточный гидрофизический характер.Тип почвы в некоторых участках – Серо-полупустынный. Характеризуется малой прослойкой гумуса (25-40 см) и низким его содержанием (2%), каменистостью и значи-тельным количеством карбонатов, гипсовыми прослоями с низким коэффициентом поглощения (20-30 мг), недостаточ-ным водно-физическим персонажем. Они богаты земляными щелочными основаниями (pH=7.5-8.5), местами имеют солевую природу.',
    'toursTitle': 'Туристические визиты',
    'toursText': 'После завершения строительных и отделочных работ особое значение будет иметь организация туристических визитов, во время которых, помимо принятой дегустации и экскурсии, будут проведены различные образовательные и информационные мастер-классы для желающих, они будут участвовать в производственных процессах и т. д.',
    'line1': "Джрагацпанян",
    'line2': "Бамбак",
  },
  en: {
    'home': 'Home',
    'about': "About",
    'tours': 'Tours',
    'history': 'About Us',
    'wines': 'Wines',
    'grapes': 'Grapes',
    'social': 'Social',
    'terroir': 'Terroir',
    'team':  'Team',
     'contact': 'Contact',
    'payment': 'payment',
    'historyTitle': 'The Jraghatspanyan History',
    'historyText': 'In Armenia, the cradle of viticulture and winemaking, 6100-year-old traditions are passed down from generation to generation, reaching our days. Having moved from Western Armenia to the Blur district of the historical capital of Armavir, famous for its ancient winemaking traditions, our ancestors planted vineyards, in 1890s built underground cellar and produced their own wine, passing on traditions to generations.Having winemaking traditions inherited from ancestors, a winemaking facility and an underground cellar, the process of making wine and combining it with food has always been an integral part of the daily life of the Jraghatspanyan family. Jraghatspanyan wines are created from a combination of sunny grape, traditional processing methods and inherited traditions. The combination of grapes harvested in the traditional atmosphere of songs and dances, passionate processing, detailed control of the fermentation process and harmonious maturation, every drop of Jragatspanyan wine is born.',
    'grapesTitle': 'Terroir',
    'grapesText': 'The grapes used for the wine production is generaly from the vinyards located closed to the winery in Bambakashat village, Armavir marz. A part of the processed grapes from our vineyards (2 ha), which we plan to expand with the using of new approaches, exclusively with Armenian varieties by the testing their wine-making potential. The winery and vineyards are located in the Ararat valley, in the village of Bambakashat, Armavir region. The village is located in the middle of the Ararat plain, has fertile lands, favorable for agriculture. Height above sea level 860m. Soil type - Alluvial gray-meadow soils were formed on the Ararat plain at an altitude of 800-950 m as a result of soil, surface moisture and centuries of human activity. The thickness of the humus layer is 80-120 cm. The soil is characterized by a high content of carbonates (3-7%) and a low content of humus (1.5-2.0%), clay and sandy loam texture. Alkaline reaction of the soil: 8.2-8.5. The soil is mostly non-saline, but there are areas of slightly saline and non-saline due to the influence of mineral waters in the subsoil. The average soil absorption coefficient is 30-40 mg. It has a sufficient hydro physical character. The soil type in some areas is gray-semi-desert. It is characterized by a small layer of humus (25-40 cm) and its low content (2%), rockiness and a significant amount of carbonates, gypsum interlayers with a low absorption coefficient (20-30 mg), insufficient water-physical character. They are rich in earthy alkaline bases (pH=7.5-8.5), in some places they have a saline nature.',
    'toursTitle': 'Tourist visits',
    'toursText': 'After the completion of construction and finishing works, the organization of tourist visits will be of particular importance, during which, in addition to the accepted tasting and excursion, various educational and informational master classes will be held for those who wish, they will participate in production processes, etc.',
    'line1': "Jraghatspanyan",
    'line2': "Bambak",
  },
}
