export const translations = {
    en: {
      contactUs: "Contact Us",
      contactSubtitle: "Do you need any support? Contact us, we'll get back to you shortly",
      getFeedback: "Get Feedback",
      feedbackSubtitle: "Leave us your message and get feedback.",
      findUsOn: "You Can Also Find Us On",
      firstName: "First Name",
      lastName: "Last Name",
      email: "Email",
      phoneNumber: "Phone Number",
      subject: "Subject",
      message: "Message",
      send: "Send",
      sending: "Sending...",
      required: "This field is required",
      invalidEmail: "Please enter a valid email address",
      submitSuccess: "Thank you! Your message has been sent successfully.",
      submitError: "Something went wrong. Please try again later.",
    },
    am: {
      contactUs: "Կապ մեզ հետ",
      contactSubtitle: "Օգնության կարիք ունե՞ք: Կապվեք մեզ հետ, մենք շուտով կպատասխանենք",
      getFeedback: "Ստացեք արձագանք",
      feedbackSubtitle: "Թողեք ձեր հաղորդագրությունը և ստացեք արձագանք։",
      findUsOn: "Դուք կարող եք նաև գտնել մեզ",
      firstName: "Անուն",
      lastName: "Ազգանուն",
      email: "Էլ․ փոստ",
      phoneNumber: "Հեռախոսահամար",
      subject: "Թեմա",
      message: "Հաղորդագրություն",
      send: "Ուղարկել",
      sending: "Ուղարկվում է...",
      required: "Այս դաշտը պարտադիր է",
      invalidEmail: "Խնդրում ենք մուտքագրել վավեր էլ․ փոստի հասցե",
      submitSuccess: "Շնորհակալություն! Ձեր հաղորդագրությունը հաջողությամբ ուղարկվել է։",
      submitError: "Ինչ-որ բան այն չէ: Խնդրում ենք փորձել ավելի ուշ:",
    },
    ru: {
      contactUs: "Свяжитесь с нами",
      contactSubtitle: "Нужна помощь? Свяжитесь с нами, мы скоро ответим",
      getFeedback: "Получить обратную связь",
      feedbackSubtitle: "Оставьте нам свое сообщение и получите обратную связь.",
      findUsOn: "Вы также можете найти нас",
      firstName: "Имя",
      lastName: "Фамилия",
      email: "Электронная почта",
      phoneNumber: "Номер телефона",
      subject: "Тема",
      message: "Сообщение",
      send: "Отправить",
      sending: "Отправка...",
      required: "Это поле обязательно",
      invalidEmail: "Пожалуйста, введите действительный адрес электронной почты",
      submitSuccess: "Спасибо! Ваше сообщение успешно отправлено.",
      submitError: "Что-то пошло не так. Пожалуйста, попробуйте позже.",
    },
  }
  